DSNS-229, 230 and 231
GeoscienceAustralia/dea-ard-scene-select pull request #77
Opened 2023-10-04 06:47 UTC by gordonyeong

DSNS-231:
        - Introduced integration tests for landset l1 data - R3.3 Filter out
          the l1 scene if there is already an ARD scene with the same scene_id,
          that is un-archived
    DSNS-230:
        1. Introduced new integration tests for s2 data - R3.2 Process a scene
           if the child is interim and ancill data is there
        2. Updated util.py's get_extracted_path() to work with s2. Also tested
           the existing tests to ensure they still work.
    DSNS-229:
        - Introduced new integration tests for s2 data - R1.1 Unfiltered scenes
        are ARD processed

2023-10-05 02:31 UTC, dunkgray requested changes
here's some suggested modifications
https://github.com/GeoscienceAustralia/dea-ard-scene-select/pull/78
Though this branch has had a forced update, so merging could be an issue

2023-10-05 02:59 UTC, gordonyeong commented
the only major difference i can see in the feature branch you have set up is just that the calls to scene select do not have `--config`, to which i didn't do because i did not want to break consistency. The original s2_go_select.sh and ls_go_select.sh did have an explicitly defined config to use.

2023-10-05 04:33 UTC, gordonyeong commented
adjustements made as discussed :) kindly review when you are ready, Duncan :)

2023-10-05 04:53 UTC, dunkgray requested changes
lets remove the file - tests/integration_tests/test_s2_scenes_r1_2.py from this PR. Potentially the requirement R1.2: S2 scenes can be processed when the zip and yaml are in different directories doesn't fit with these tests.
why is tests/integration_tests/test_scene_r_2_7.py and tests/integration_tests/test_scene_r_2_6.py being deleted?

2023-10-05 22:23 UTC, gordonyeong commented
lets remove the file - tests/integration_tests/test_s2_scenes_r1_2.py from this PR. Potentially the requirement R1.2: S2 scenes can be processed when the zip and yaml are in different directories doesn't fit with these tests.

  *   I can do this but does that mean we cancel DSNS-239 ?


________________________________
From: Duncan Gray ***@***.***>
Sent: Thursday, 5 October 2023 3:53 PM
To: GeoscienceAustralia/dea-ard-scene-select ***@***.***>
Cc: Gordon Yeong ***@***.***>; Author ***@***.***>
Subject: Re: [GeoscienceAustralia/dea-ard-scene-select] DSNS-229, 230 and 231 (PR #77)


@dunkgray requested changes on this pull request.

lets remove the file - tests/integration_tests/test_s2_scenes_r1_2.py from this PR. Potentially the requirement R1.2: S2 scenes can be processed when the zip and yaml are in different directories doesn't fit with these tests.
why is tests/integration_tests/test_scene_r_2_7.py and tests/integration_tests/test_scene_r_2_6.py being deleted?

—
Reply to this email directly, view it on GitHub<https://github.com/GeoscienceAustralia/dea-ard-scene-select/pull/77#pullrequestreview-1658874068>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5NATHIZKB6FLJBTCX2TJBTX5Y4NXAVCNFSM6AAAAAA5SDKJ4KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJYHA3TIMBWHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.

2023-10-05 22:23 UTC, gordonyeong commented
> lets remove the file - tests/integration_tests/test_s2_scenes_r1_2.py from this PR. Potentially the requirement R1.2: S2 scenes can be processed when the zip and yaml are in different directories doesn't fit with these tests.



Does this mean that DSNS-239 is to be cancelled?

2023-10-05 23:00 UTC, dunkgray commented
re: lets remove the file - tests/integration_tests/test_s2_scenes_r1_2.py from this PR. Potentially the requirement R1.2: S2 scenes can be processed when the zip and yaml are in different directories doesn't fit with these tests.

Does this mean that DSNS-239 is to be cancelled?

potentially, but let's get the .py out of this PR first

2023-10-06 00:24 UTC, dunkgray requested changes
why is tests/integration_tests/test_scene_r_2_7.py being deleted?
Also, if commits are kept separate it help's me understand what the change is. So let's have individual commits. They can get squashed in the merge.

2023-10-06 00:24 UTC, dunkgray commented on tests/integration_tests/test_s2_r3_2.py
> +    matching_files = list(Path(tmp_path).glob("filter-jobid-*/" + GEN_LOG_FILE))
lines 150 - 152 can go.

2023-10-06 00:32 UTC, gordonyeong commented
that was deleted because it was a copy of
  tests/integration_tests/test_scene_r_2_6.py.I squashed them in readiness of a final review. Alright, i will leave the commits in their original forms.


________________________________
From: Duncan Gray ***@***.***>
Sent: Friday, 6 October 2023 11:24 AM
To: GeoscienceAustralia/dea-ard-scene-select ***@***.***>
Cc: Gordon Yeong ***@***.***>; Author ***@***.***>
Subject: Re: [GeoscienceAustralia/dea-ard-scene-select] DSNS-229, 230 and 231 (PR #77)


@dunkgray requested changes on this pull request.

why is tests/integration_tests/test_scene_r_2_7.py being deleted?
Also, if commits are kept separate it help's me understand what the change is. So let's have individual commits. They can get squashed in the merge.

________________________________

In tests/integration_tests/test_s2_r3_2.py<https://github.com/GeoscienceAustralia/dea-ard-scene-select/pull/77#discussion_r1348122232>:

> +    ]
+
+    runner = CliRunner()
+    result = runner.invoke(
+        scene_select,
+        args=cmd_params,
+    )
+
+    assert (
+        result.exit_code == 0
+    ), f"The scene_select process failed to execute: {result.output}"
+    assert result.output != "", f" the result output is {result.output}"
+
+    # Use glob to search for the log file
+    # within filter-jobid-* directories
+    matching_files = list(Path(tmp_path).glob("filter-jobid-*/" + GEN_LOG_FILE))


lines 150 - 152 can go.

—
Reply to this email directly, view it on GitHub<https://github.com/GeoscienceAustralia/dea-ard-scene-select/pull/77#pullrequestreview-1660945609>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5NATHNHFMYNO2JPJSDI2STX55FVJAVCNFSM6AAAAAA5SDKJ4KVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRQHE2DKNRQHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.

2023-10-06 00:42 UTC, gordonyeong commented on tests/integration_tests/test_s2_r3_2.py
> +    matching_files = list(Path(tmp_path).glob("filter-jobid-*/" + GEN_LOG_FILE))
sorted.

2023-10-06 00:45 UTC, dunkgray commented
> deleted because it was a copy of
  tests/integration_tests/test_scene_r_2_6.py
ok, thanks.

2023-10-06 01:03 UTC, dunkgray approved these changes

2023-10-06 01:05 UTC, merged