DSNS 269: Removal of hard coded user config files and references
GeoscienceAustralia/dea-ard-scene-select pull request #89
Opened 2023-10-26 04:11 UTC by gordonyeong

1. Removal of hard coded user config files and references.
        This removes the manual dependency of ensuring config files
        specific to the user has to exist in the repository. Instead,
        new code has been introduced to generate and clean up the
        dynamically generated config files on the fly for the specific
        user running the script(s), and
      2. Deprecated the following as they are no longer used:
         -dea-ard-scene-select/tests/ard_reprocessed_l1s/dev_go_reprocess.sh:
            retired as it has been superseeded by auto_run_test_ard_reprocessed_l1s.sh
         -dea-ard-scene-select/tests/ard_reprocessed_l1s: retired all files
            except for tests/ard_reprocessed_l1s/auto_run_test_ard_reprocessed_l1s.sh
            and its related files. Ran the tests/ard_reprocessed_l1s/auto_run_test_ard_reprocessed_l1s.sh
            test and it persists in running without errors.

2023-10-26 06:16 UTC, dunkgray requested changes
This PR has suggestions.
Consider approving and merging this PR onto this branch. 
https://github.com/GeoscienceAustralia/dea-ard-scene-select/pull/90

2023-10-26 20:26 UTC, gordonyeong reviewed
hi, duncan, good morning. I have checked out the changes and ran the db_index.sh and check_db.sh in ard_tests. 

however, i did remove ard_tests/test.sh after development because i was just using it for my dev.

2023-10-26 20:26 UTC, gordonyeong commented on tests/ard_tests/test.sh
hi, duncan, good morning. i did remove ard_tests/test.sh after development because i was just using it for my dev.  Kindly delete it as it's not a full fledge test :) haha thank you :)

2023-10-26 23:55 UTC, dunkgray approved these changes
looks good

2023-10-27 00:51 UTC, gordonyeong commented
thank you, Duncan :)

2023-10-27 00:52 UTC, merged